""" Desafio 080 - Crie um programa onde o usuário possa digitar cinco valores numéricos e cadastre-os em uma lista, já
    na posição correta de inserção (sem usar o sort()). No final, mostre a lista ordenada na tela.

    Digite um valor: 7
    Adicionado no final da lista...
    Digite um valor: 2
    Adicionado na posição 0 da lista...
    Digite um valor: 5
    Adicionado na posição 1 da lista...
    Digite um valor: 9
    Adicionado no final da lista...
    Digite um valor: 3
    Adicionado na posição 1 da lista...
    =-==-==-==-==-==-==-==-==-==-==-==-==-==-==-==-==-==-==-==-==-==-=
    O valores digitados em ordem foram [2, 3, 5, 7, 9] """